arb-dir: lib/core/localizations
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localizations
synthetic-package: false