Map<String, String> locale = {
  'Let’s Get Started!': 'Давайте начнем!',
  'Let’s dive in into your account': 'Давайте войдем в ваш аккаунт',
  'Continue with Google': 'Продолжить с Google',
  'Continue with Apple': 'Продолжить с Apple',
  'Continue with Facebook': 'Продолжить с Facebook',
  'Continue with Twitter': 'Продолжить с Twitter',
  'Sign up': 'Зарегистрироваться',
  'Sign in': 'Войти',
  'Privacy Policy': 'Политика конфиденциальности',
  'Terms of Service': 'Условия использования',
  'Create New Habit': 'Создать новую привычку',
  'Regular Habit': 'Обычная привычка',
  'One-Time Task': 'Одноразовая задача',
  'Habit Name': 'Название привычки',
  'Study Art': 'Изучать искусство',
  'Icon': 'Иконка',
  'Color': 'Цвет',
  'Repeat': 'Повторять',
  'Daily': 'Ежедневно',
  'Weekly': 'Еженедельно',
  'Monthly': 'Ежемесячно',
  'Every month on 3, 8, 13, 17, 22, 27, 31':
      'Каждый месяц 3, 8, 13, 17, 22, 27, 31',
  'Do it at:': 'Выполнять в:',
  'Morning': 'Утро',
  'Afternoon': 'День',
  'Evening': 'Вечер',
  'End Habit on': 'Завершить привычку',
  'Save': 'Сохранить',
  "Report": "Отчет",
  "226 days": "226 дней",
  "Streak": "Серия",
  "89%": "89%",
  "Completion Rate": "Процент выполнения",
  "3,268": "3,268",
  "Total Habits Completed": "Всего выполнено привычек",
  "307": "307",
  "Total Habits Completed This Week": "Всего выполнено привычек на этой неделе",
  "Habits Completed": "Выполненные привычки",
  "This Week": "На этой неделе",
  "Habit Completion Rate": "Процент выполнения привычек",
  "Last 6 Months": "Последние 6 месяцев",
  "Calendar Stats": "Статистика календаря",
  "This Month": "Этот месяц",
  "Mood Chart": "График настроения"
};
